version: 3

tasks:
  sync:
    cmds:
      - uv sync --group dev

  lock:
    cmds:
      - uv lock

  bump:
    vars:
      VERSION:
        sh: yq '.project.version' pyproject.toml
    cmds:
      - git add pyproject.toml
      - 'git commit -m "bump: {{.VERSION}}"'
      - 'git tag "v{{.VERSION}}" -m "v{{.VERSION}}"'
